export const AI_MODELS = [
  {
    id: 'glm-4.7-coder',
    name: 'GLM-4.7 Coder',
    provider: 'Zhipu AI',
    icon: 'code-slash',
    description: 'Chinese coding model with strong performance',
  },
  {
    id: 'glm-4-coder',
    name: 'GLM-4 Coder',
    provider: 'Zhipu AI',
    icon: 'code-working',
    description: 'Fast Chinese coding assistant',
  },
  {
    id: 'local-qwen2.5-coder-1.5b',
    name: 'Local Qwen2.5 Coder 1.5B',
    provider: 'On-device',
    icon: 'phone-portrait',
    description: 'Offline model (auto-download)',
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    icon: 'flash',
    description: 'Ultra-fast with thinking capabilities',
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    icon: 'trophy',
    description: 'Advanced reasoning with 1M tokens',
  },
  {
    id: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'Google',
    icon: 'flash-outline',
    description: 'Fast and efficient',
  },
  {
    id: 'claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    icon: 'sparkles',
    description: 'Most capable model for complex tasks',
  },
  {
    id: 'claude-3-haiku',
    name: 'Claude 3 Haiku',
    provider: 'Anthropic',
    icon: 'flash',
    description: 'Fast and lightweight',
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    icon: 'bulb',
    description: 'OpenAI\'s flagship model',
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    icon: 'flash-outline',
    description: 'Fast and cost-effective',
  },
  {
    id: 'openrouter/google/gemma-3-1b-it',
    name: 'Gemma 3 1B',
    provider: 'Google (OR)',
    icon: 'logo-google',
    description: 'Lightweight multimodal model',
  },
  {
    id: 'openrouter/openai/gpt-oss-20b',
    name: 'GPT-OSS 20B',
    provider: 'OpenAI (OR)',
    icon: 'logo-github',
    description: 'Open-weight MoE model',
  },
  {
    id: 'openrouter/deepseek/deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'DeepSeek (OR)',
    icon: 'code-working',
    description: 'Powerful reasoning model',
  },
  {
    id: 'openrouter/google/gemini-2.0-flash-exp:free',
    name: 'Gemini 2.0 Flash Free',
    provider: 'Google (OR)',
    icon: 'flash',
    description: 'Free experimental model',
  },
];
