export const AI_MODELS = [
  {
    id: 'local-qwen2.5-coder-1.5b',
    name: 'Local Qwen2.5 Coder 1.5B',
    provider: 'On-device',
    icon: 'phone-portrait',
    description: 'Offline model (auto-download)',
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    icon: 'flash',
    description: 'Ultra-fast with thinking capabilities',
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    icon: 'trophy',
    description: 'Advanced reasoning with 1M tokens',
  },
  {
    id: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'Google',
    icon: 'flash-outline',
    description: 'Fast and efficient',
  },
  {
    id: 'claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    icon: 'sparkles',
    description: 'Most capable model for complex tasks',
  },
  {
    id: 'claude-3-haiku',
    name: 'Claude 3 Haiku',
    provider: 'Anthropic',
    icon: 'flash',
    description: 'Fast and lightweight',
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    icon: 'bulb',
    description: 'OpenAI\'s flagship model',
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    icon: 'flash-outline',
    description: 'Fast and cost-effective',
  },
];
